Add pkg-config supprt
ARM-software/AArch64cryptolib pull request #1
Opened 2020-10-27 04:15 UTC by dhatha01

Update Makefile to generate 'libAArch64crypto.pc' in 'pkgconfig'
directory on calling 'make'.

To build applications against this library, set the appropriate path
to libAArch64crypto.pc in PKG_CONFIG_PATH environment variable.

Signed-off-by: Dharmik Thakkar <dharmik.thakkar@arm.com>

2020-11-03 14:14 UTC, WonderfulVoid commented on Makefile
> +PACKAGE_DESCRIPTION=AArch64 Cypto Library
Cypto -> Crypto

2020-11-03 14:15 UTC, WonderfulVoid requested changes
Fix spelling error.

2020-11-03 22:55 UTC, dhatha01 commented on Makefile
> +PACKAGE_DESCRIPTION=AArch64 Cypto Library
Done

2020-11-04 14:38 UTC, WonderfulVoid approved these changes
LGTM

2020-11-04 14:38 UTC, merged